# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: app-db
spec:
  # Replicas for this Deployment
  replicas: 2
  selector:
    # labels the pods
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: app-db
    spec:
      containers:
        # The container name to execute pods
        - name: app-db
          # pull postgresimage from docker hub
          image: postgres
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: app-db-secret-credentials
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgres/data
              name: app-db-data
      # Volumes attached to the pod
      volumes:
        - name: app-db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: app-db-persistent-volume-claim
